migrate(
  (db) => {
    const snapshot = [
      {
        id: "_pb_users_auth_",
        created: "2023-02-06 17:24:43.240Z",
        updated: "2023-02-07 03:34:43.342Z",
        name: "users",
        type: "auth",
        system: false,
        schema: [
          {
            system: false,
            id: "users_name",
            name: "display_name",
            type: "text",
            required: true,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: "",
            },
          },
          {
            system: false,
            id: "users_avatar",
            name: "avatar",
            type: "file",
            required: false,
            unique: false,
            options: {
              maxSelect: 1,
              maxSize: 5242880,
              mimeTypes: [
                "image/jpg",
                "image/jpeg",
                "image/png",
                "image/svg+xml",
                "image/gif",
                "image/webp",
              ],
              thumbs: null,
            },
          },
          {
            system: false,
            id: "2sworciw",
            name: "profile_desciption",
            type: "text",
            required: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: "",
            },
          },
          {
            system: false,
            id: "puls6cxx",
            name: "profile_picture",
            type: "file",
            required: false,
            unique: false,
            options: {
              maxSelect: 1,
              maxSize: 5242880,
              mimeTypes: [],
              thumbs: [],
            },
          },
          {
            system: false,
            id: "qyvld1ox",
            name: "is_admin",
            type: "bool",
            required: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: "grfnvvd7",
            name: "last_login_time",
            type: "date",
            required: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
        ],
        listRule: "id = @request.auth.id",
        viewRule: "id = @request.auth.id",
        createRule: "",
        updateRule: "id = @request.auth.id",
        deleteRule: "id = @request.auth.id",
        options: {
          allowEmailAuth: true,
          allowOAuth2Auth: true,
          allowUsernameAuth: true,
          exceptEmailDomains: null,
          manageRule: null,
          minPasswordLength: 8,
          onlyEmailDomains: null,
          requireEmail: false,
        },
      },
      {
        id: "1f0s4wonydz4yqj",
        created: "2023-02-06 18:21:24.995Z",
        updated: "2023-02-07 03:34:43.343Z",
        name: "tweet_text",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "exiiuwht",
            name: "tweet_text",
            type: "text",
            required: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: "",
            },
          },
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "nljhld5o2yprnfb",
        created: "2023-02-06 18:21:35.545Z",
        updated: "2023-02-07 03:34:43.343Z",
        name: "tweets",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "mw34gypa",
            name: "user_id",
            type: "relation",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "_pb_users_auth_",
              cascadeDelete: true,
            },
          },
          {
            system: false,
            id: "ve5428cb",
            name: "is_public",
            type: "bool",
            required: false,
            unique: false,
            options: {},
          },
          {
            system: false,
            id: "7blg8wal",
            name: "tweet_text_id",
            type: "relation",
            required: true,
            unique: true,
            options: {
              maxSelect: 1,
              collectionId: "1f0s4wonydz4yqj",
              cascadeDelete: false,
            },
          },
          {
            system: false,
            id: "wruaahwc",
            name: "scheduled_at",
            type: "date",
            required: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
          {
            system: false,
            id: "lvqv0ftm",
            name: "published_at",
            type: "date",
            required: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "y6temtc9xn7joel",
        created: "2023-02-06 18:37:42.321Z",
        updated: "2023-02-07 03:34:43.343Z",
        name: "hashtags",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "kyqcvmab",
            name: "hashtag_text",
            type: "text",
            required: true,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: "",
            },
          },
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "51phvru2fhos55v",
        created: "2023-02-06 18:53:03.599Z",
        updated: "2023-02-07 03:34:43.343Z",
        name: "tweet_hashtags",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "v0vipcgw",
            name: "hashtag_id",
            type: "relation",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "y6temtc9xn7joel",
              cascadeDelete: false,
            },
          },
          {
            system: false,
            id: "fsgbd4ps",
            name: "tweet_id",
            type: "relation",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "nljhld5o2yprnfb",
              cascadeDelete: false,
            },
          },
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "tv7xis1j3rjo080",
        created: "2023-02-06 18:57:40.535Z",
        updated: "2023-02-07 03:34:43.343Z",
        name: "following",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "v28zford",
            name: "user_id",
            type: "relation",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "_pb_users_auth_",
              cascadeDelete: true,
            },
          },
          {
            system: false,
            id: "y8hzyylf",
            name: "follower_id",
            type: "relation",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "_pb_users_auth_",
              cascadeDelete: true,
            },
          },
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "sn8xerdxcew7lkv",
        created: "2023-02-06 19:02:43.079Z",
        updated: "2023-02-07 03:34:43.343Z",
        name: "likes",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "q4mjfjau",
            name: "user_id",
            type: "relation",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "_pb_users_auth_",
              cascadeDelete: true,
            },
          },
          {
            system: false,
            id: "k58a3k6o",
            name: "tweet_id",
            type: "relation",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "nljhld5o2yprnfb",
              cascadeDelete: true,
            },
          },
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "ah3l45gtcb2jrsy",
        created: "2023-02-06 19:08:21.233Z",
        updated: "2023-02-07 13:28:06.351Z",
        name: "reply",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "ievoolwh",
            name: "retweet",
            type: "relation",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "nljhld5o2yprnfb",
              cascadeDelete: false,
            },
          },
          {
            system: false,
            id: "mffyu7m7",
            name: "original_tweet",
            type: "relation",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "nljhld5o2yprnfb",
              cascadeDelete: false,
            },
          },
          {
            system: false,
            id: "phnacp3v",
            name: "post_on_profile",
            type: "bool",
            required: false,
            unique: false,
            options: {},
          },
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "jhvziaei06toeym",
        created: "2023-02-06 19:17:54.900Z",
        updated: "2023-02-07 03:34:43.343Z",
        name: "tweet_attachments",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "yqtvcajk",
            name: "file",
            type: "file",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              maxSize: 5242880,
              mimeTypes: [],
              thumbs: [],
            },
          },
          {
            system: false,
            id: "comocegn",
            name: "type",
            type: "select",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["image", "video", "voice", "other"],
            },
          },
          {
            system: false,
            id: "twniyvre",
            name: "field",
            type: "relation",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "nljhld5o2yprnfb",
              cascadeDelete: false,
            },
          },
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "w6j93wsiq9yu2iw",
        created: "2023-02-06 19:20:08.668Z",
        updated: "2023-02-07 03:34:43.343Z",
        name: "polls",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "anu7n8pw",
            name: "tweet_id",
            type: "relation",
            required: true,
            unique: true,
            options: {
              maxSelect: 1,
              collectionId: "nljhld5o2yprnfb",
              cascadeDelete: true,
            },
          },
          {
            system: false,
            id: "9urfvu6w",
            name: "end_time",
            type: "date",
            required: false,
            unique: false,
            options: {
              min: "",
              max: "",
            },
          },
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "dn5kqk2tv06fidr",
        created: "2023-02-06 19:21:52.619Z",
        updated: "2023-02-07 03:34:43.343Z",
        name: "poll_options",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "qpgrttix",
            name: "option_text",
            type: "text",
            required: true,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: "",
            },
          },
          {
            system: false,
            id: "adkykibj",
            name: "poll_id",
            type: "relation",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "w6j93wsiq9yu2iw",
              cascadeDelete: true,
            },
          },
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "ebvjgj18kit6asn",
        created: "2023-02-06 19:23:56.225Z",
        updated: "2023-02-07 03:34:43.343Z",
        name: "voting",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "2y8nuo7t",
            name: "user_id",
            type: "relation",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "_pb_users_auth_",
              cascadeDelete: false,
            },
          },
          {
            system: false,
            id: "n6hustex",
            name: "poll_options_id",
            type: "relation",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "dn5kqk2tv06fidr",
              cascadeDelete: false,
            },
          },
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "bqvvr0ryd1osc5z",
        created: "2023-02-06 19:27:57.642Z",
        updated: "2023-02-07 03:34:43.343Z",
        name: "msg_content",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "subuqwtf",
            name: "content",
            type: "text",
            required: false,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: "",
            },
          },
          {
            system: false,
            id: "bg09mhge",
            name: "type",
            type: "select",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              values: ["text", "image", "video", "voice", "files"],
            },
          },
          {
            system: false,
            id: "bntpqwh5",
            name: "file",
            type: "file",
            required: false,
            unique: false,
            options: {
              maxSelect: 1,
              maxSize: 5242880,
              mimeTypes: [],
              thumbs: [],
            },
          },
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "ydq7kgj1cg488ia",
        created: "2023-02-06 19:32:22.422Z",
        updated: "2023-02-07 03:34:43.343Z",
        name: "group_chats",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "3amvncdd",
            name: "name",
            type: "text",
            required: true,
            unique: false,
            options: {
              min: null,
              max: null,
              pattern: "",
            },
          },
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "9v9tf6kg2cgltf1",
        created: "2023-02-06 19:32:28.253Z",
        updated: "2023-02-07 03:34:43.343Z",
        name: "conversations",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "7vvyv7kv",
            name: "content_id",
            type: "relation",
            required: false,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "bqvvr0ryd1osc5z",
              cascadeDelete: true,
            },
          },
          {
            system: false,
            id: "8hplujfv",
            name: "sender_id",
            type: "relation",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "_pb_users_auth_",
              cascadeDelete: false,
            },
          },
          {
            system: false,
            id: "a0olkoxh",
            name: "receiver_id",
            type: "relation",
            required: false,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "_pb_users_auth_",
              cascadeDelete: false,
            },
          },
          {
            system: false,
            id: "eyw8msr5",
            name: "group_id",
            type: "relation",
            required: false,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "ydq7kgj1cg488ia",
              cascadeDelete: false,
            },
          },
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
      {
        id: "x4g6qae8vv03v6w",
        created: "2023-02-06 19:33:41.842Z",
        updated: "2023-02-07 03:34:43.343Z",
        name: "group_chat_members",
        type: "base",
        system: false,
        schema: [
          {
            system: false,
            id: "tfkahke8",
            name: "user_id",
            type: "relation",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "_pb_users_auth_",
              cascadeDelete: false,
            },
          },
          {
            system: false,
            id: "prnqoyvu",
            name: "group_id",
            type: "relation",
            required: true,
            unique: false,
            options: {
              maxSelect: 1,
              collectionId: "ydq7kgj1cg488ia",
              cascadeDelete: true,
            },
          },
        ],
        listRule: null,
        viewRule: null,
        createRule: null,
        updateRule: null,
        deleteRule: null,
        options: {},
      },
    ];

    const collections = snapshot.map((item) => new Collection(item));

    return Dao(db).importCollections(collections, true, null);
  },
  (db) => {
    return null;
  }
);
