#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

function changed {
  git diff --name-only HEAD@{1} HEAD | grep "^$1" > /dev/null 2>&1
}

if changed 'pnpm-lock.yaml'; then
  echo "📦 pnpm-lock.yaml changed. Running 'pnpm i' to bring your dependencies up to date."
  pnpm i
fi
