name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    permissions:
      # only required for workflows in private repositories
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: build
        run: pnpm run build

      # - name: Deploy to AWS
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.AWS_EC2_RSA_KEY }}
      #     REMOTE_HOST: ${{ secrets.AWS_HOST }}
      #     REMOTE_USER: ${{ secrets.AWS_USERNAME }}
      #     SOURCE: "dist/"
      #     TARGET: ~/my-project
