name: Lint

on: [push]

jobs:
  check-files:
    name: check files change
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changed-files-specific.outputs.any_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Get changed code files
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: |
            ./**/*.{js, jsx, json, css, scss, tsx, ts}
            pnpm-lock.yaml

      - name: print out changed
        run: echo ${{ steps.changed-files-specific.outputs.any_changed }}

  lint:
    name: lint and format
    needs: check-files
    if: success() && ${{ needs.check-files.outputs.changed }} == "true"
    runs-on: ubuntu-latest
    permissions:
      # only required for workflows in private repositories
      contents: write
    steps:
      - name: print out changed
        run: echo ${{ needs.check-files.outputs.changed }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run Linter and fix
        run: pnpm run lint:fix

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: :robot: autofix code by github action"
