name: Prettier

on: [push]
jobs:
  prettier:
    name: prettier
    runs-on: ubuntu-latest
    permissions:
      # only required for workflows in private repositories
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.head_ref }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier to format
        run: pnpm exec prettier --write --ignore-unknown .

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: success() && github.ref == 'refs/heads/main'
        with:
          commit_message: "style: :robot: prettier code by github action"
          push_options: --force

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: success() && github.ref != 'refs/heads/main'
        with:
          commit_message: "style: :robot: prettier code by github action"
